### ISSUE TITLE
Map behavior is inconsistent

### ISSUE THREAD

**Issue by poroszd** [debasishg/scala-redis#122]
Currently hmset and hgetall don't seem to match up very well:

    scala> redis.get("xyz")
    res4: Option[String] = None

    scala> redis.hgetall("xyz")
    res5: Option[Map[String,String]] = Some(Map())

    scala> redis.hmset("xyz", Map.empty[String, String])
    java.lang.Exception: ERR wrong number of arguments for 'hmset' command

It might be more intuitive if they would be symmetrical, like either

* setting an empty map fails, but getting an absent key returns `None`, or
* setting an empty map is handled without error, and getting an absent key returns simply `Map.empty`, not `Some(Map.empty)`

**Comment by pheaver** [comment]
Yeah, I ran into this problem today. What is the meaning of None in hgetall if it returns Some for non-existent keys?

**Comment by fancellu** [comment]
I just stumbled upon this. It should return None or Some(NonEmptyMap)

Give the lack of response on this, doesn't look like it's going to be fixed.

**Comment by debasishg** [comment]
Let me take another look. The scary part is the change in API semantics. I
do understand the asymmetry though. Do u think we should make this breaking
change ?

On Monday 11 January 2016, Dino Fancellu <notifications@github.com> wrote:

> I just stumbled upon this. It should return None or Some(NonEmptyMap)
>
> Give the lack of response on this, doesn't look like it's going to be
> fixed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/debasishg/scala-redis/issues/122#issuecomment-170596007>
> .
>


-- 
Sent from my iPhone

**Comment by poroszd** [comment]
Well, you can always introduce a new method, working symetrically as expected, and make this one deprecated.

**Comment by debasishg** [comment]
Yes .. That's what I was thinking too .. Only that I lose the
current symmetry of API naming. But that's possibly the best option now.
Will do it ASAP.

On Monday 11 January 2016, poroszd <notifications@github.com> wrote:

> Well, you can always introduce a new method, working symetrically as
> expected, and make this one deprecated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/debasishg/scala-redis/issues/122#issuecomment-170599191>
> .
>


-- 
Sent from my iPhone

**Comment by fancellu** [comment]
You could create a new method. Or you have it take a implicit param to decide on the behaviour, where it defaults to the old behaviour

e.g.

```
sealed trait Behavior
object Behaviors{
 implicit case object NewB extends Behavior
 implicit case object OldB extends Behavior
}
def hgetall(key:String,value:String)(implicit behave:Behavior=Behaviors.OldB)={
 println(behave)
}  

hgetall("xxx","yyy")                              //> OldB
import Behaviors.NewB
hgetall("xxx","yyy")                              //> NewB
```

**Comment by fancellu** [comment]
That way nothing will break existing code, but all it takes is a simple 
    import Behaviors.NewB

or whatever who choose to name it

**Comment by debasishg** [comment]
@fancellu This is a difficult to scale convention to evolve APIs and impacts clients more invasively. No one likes to import implicits :-) .. I think a simpler and better option will be to rename the API to `hgetall1` and mark `hgetall` deprecated. Maybe once we remove `hgetall` we can bring it back through another level of deprecation.

**Comment by debasishg** [comment]
Created a PR https://github.com/debasishg/scala-redis/pull/160. Changed semantics, the new API is named `hgetall1` with `hgetall` deprecated. Setting of an empty Map is an error and `hgetall1` for a non-existing key returns `None`. Feedback ?

**Comment by debasishg** [comment]
merged
