### ISSUE TITLE
Enable pipelining of PUBLISH commands

### ISSUE THREAD

**Issue by bmironenko** [debasishg/scala-redis#135]
It would be helpful if PUBLISH commands could be pipelined, especially since the return result is mostly useless. As of right now, this is implemented by the PubSub trait, which unfortunately is not part of the PipelineClient.

**Comment by debasishg** [comment]
Thanks for reporting .. Looks like a good option to have .. let me put this in my schedule.

**Comment by debasishg** [comment]
Fixed on master .. Please check if it works for you.
