### ISSUE TITLE
New (maven) release request

### ISSUE THREAD

**Issue by zifeo** [debasishg/scala-redis#157]
Due to [this bug](https://github.com/debasishg/scala-redis/commit/463adb1b24d7f48211bafecbf2278d9048499909#diff-88aa0ef9dec8a1a9e3c1b957cfa08d83) the current version is unusable on maven as no client pooling can happen if the selected database is different from `0`. Is there any other repository where we could get a version higher than `3.0` (local is not an option for us)?

Thanks for the work!

**Comment by debasishg** [comment]
Released 3.1 just now .. Maven Central should have it after syncing ..

**Comment by zifeo** [comment]
Works fine, thanks!
