### ISSUE TITLE
Disabling the Logger

### ISSUE THREAD

**Issue by aldolipani** [debasishg/scala-redis#164]
How do I disable the logger? It is set by default at DEBUG level.

**Comment by debasishg** [comment]
The redis server log level can be set in `redis.conf` ..

**Comment by aldolipani** [comment]
Thank you for the answer, but actually my problem was another one, totally unrelated to the use of this library (`debasishg/scala-redis`).

I'll explain it here just in case somebody else will encounter it.

My context is: Intellij IDEA 14.1.6 CE, working on a sbt project, using managed libraries in which one of the jars contains a `log4j.properties` file configuration, and a need to create a jar artefact. The problem was that in the process of creation the jar artefact, the log4j.properties configuration in the managed library rewrites the `log4j.properties` of the project. To solve it I took a version of the library without the `log4j.properties` file in it.

Thank you again, and thank you also for the effort employed in creating such a useful library.
