### ISSUE TITLE
Getting all the keys

### ISSUE THREAD

**Issue by danyaljj** [debasishg/scala-redis#168]
Is there a way to get all the keys stored in redis?

**Comment by danyaljj** [comment]
Found it: https://github.com/debasishg/scala-redis/blob/master/src/main/scala/com/redis/Operations.scala#L49 
Would be nice to add samples to the documentation.

**Comment by colinbes** [comment]
I thought using "keys" was discouraged in production releases and "scan" was recommended instead?
