### ISSUE TITLE
Are Publisher/Subscriber meant to be consumed by users?

### ISSUE THREAD

**Issue by dskrvk** [debasishg/scala-redis#200]
`PubSubServer.scala` introduces a dependency on Akka for the sake of what seems to be a demo implementation. There can be different ways to consume the client's pub/sub operations, but it seems wrong for the library to force consumers to use a particular framework.

My proposal is to move `PubSubServer.scala` into tests or a separate `examples` module that is not published with the main library, thus removing a compile dependency on `akka` (which is pretty old by now). The code could also be made part of the README to demonstrate one of the possible ways of using this functionality.

If one of these options is acceptable, I can submit a PR.

**Comment by debasishg** [comment]
I am +1 with this suggestion. The only concern is existing user base already using this. But, as u said, the akka dependency is old. So we can try that. Please submit a PR.

**Comment by dskrvk** [comment]
I searched for usages on Github (not the full picture of course, but hopefully a representative sample) and only found a few old (updated >3-4 years ago) "toy" repos that use these types.

I also found this: https://github.com/debasishg/akka-redis-pubsub What were your plans with it? Should we just move the updated PubSubServer code there?

In general, how do we handle existing consumers? Assuming this will be a new minor version in any case, I see a couple of options:
1. Considering the type of repos using this code, it's probably OK to just break them. There's a chance, however, that some private (e.g. corporate) repos seriously depend on this. Do you have a specific policy on this?
2. Annotate the types as deprecated and remove after a couple of versions from now. Considering there haven't been new versions in a while, this could take a long time.

**Comment by debasishg** [comment]
> Annotate the types as deprecated and remove after a couple of versions from now. Considering there haven't been new versions in a while, this could take a long time.

We can deprecate in the next version and follow it up with a quick update on the version.

**Comment by dskrvk** [comment]
Sounds good.
