### ISSUE TITLE
[Feature] Support for TLS

### ISSUE THREAD

**Issue by danielwpz** [debasishg/scala-redis#230]
Hey,

Looks like your library doesn't support TLS connection with Redis. Do you have any plan to add this feature?

**Comment by jojo19893** [comment]
Redis does not support native TLS https://redis.io/topics/security

**Comment by danielwpz** [comment]
yeah that I know. But cloud providers such as AWS has already enabled TLS feature for Redis(elastic cache). What shall I do if I wanna use it with TLS?

**Comment by danielwpz** [comment]
So sounds like you don't have any plan on this? If that's the case we will switch to another lib, just wanna confirm.

**Comment by stsatlantis** [comment]
Sorry for asking the following question here. I don't want to be disrespectful: @danielwpz which library provided you this functionality?
