### ISSUE TITLE
incorrect tag name on GitHub. s/v3.3.0/v3.30/

### ISSUE THREAD

**Issue by xuwei-k** [debasishg/scala-redis#263]
https://github.com/debasishg/scala-redis/tags

latest version should be v3.30 🤔 

![スクリーンショット 2020-10-15 12 48 03](https://user-images.githubusercontent.com/389787/96074867-b069fb00-0ee4-11eb-8595-6120b06d32bb.png)

**Comment by debasishg** [comment]
Thanks for pointing it out .. Updated
