### ISSUE TITLE
QUESTION - should `RedisClient` be shared or used as a singleton?

### ISSUE THREAD

**Issue by reynoldsm88** [debasishg/scala-redis#289]
To elaborate, if I am creating multiple processors (eg: Akka Actors) that need to interact with Redis, can I reuse the `RedisClient` instance or should each processor spawn it's own instance?

**Comment by noahlz** [comment]
RedisClients should not be shared between threads, and there is a `RedisClientPool` provided with the library to facilitate safe concurrent programming.

**Comment by noahlz** [comment]
See "Using Client Pooling" in the readme
